import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

export const aiDocs: ComponentDoc[] = [
  {
    slug: "ai-voice",
    name: "AI Voice",
    exportName: "AiVoice",
    description: "Voice activity visualizer for AI assistants: a breathing orb, equalizer bars, a flowing wave or bouncing dots, driven by the microphone, simulated speech or your own level.",
    category: "AI",
    file: "registry/new-york/ai-voice/ai-voice.tsx",
    dependencies: ["motion", "lucide-react"],
    isNew: true,
    props: [
      { name: "variant", type: '"orb" | "bars" | "wave" | "dots"', default: "orb", description: "Visual style.", control: { type: "select", options: ["orb", "bars", "wave", "dots"] } },
      { name: "source", type: '"mic" | "simulated" | "level"', default: "simulated", description: "Where the level comes from: the microphone (Web Audio analyser), smooth seeded noise, or the level prop.", control: { type: "select", options: ["simulated", "mic", "level"] } },
      { name: "state", type: '"idle" | "listening" | "thinking" | "speaking"', default: "speaking", description: "Idle breathes slowly, thinking rotates a shimmer, listening and speaking react to audio. Speaking uses the accent color.", control: { type: "select", options: ["idle", "listening", "thinking", "speaking"] } },
      { name: "level", type: "number", default: 0, description: "Controlled level from 0 to 1, used when source is \"level\".", control: num(0, 1, 0.05), demo: 0.5 },
      { name: "active", type: "boolean", description: "Controls the microphone when source is \"mic\". Leave undefined to use the built-in toggle." },
      { name: "color", type: "string", default: "currentColor", description: "Base color for idle and listening (any CSS color).", control: { type: "color" } },
      { name: "accent", type: "string", default: "#ff4d12", description: "Color for speaking and the thinking shimmer.", control: { type: "color" } },
      { name: "size", type: "number", default: 120, description: "Size in px. The orb is square; other variants are twice as wide as tall.", control: num(64, 240, 4, "px") },
      { name: "bars", type: "number", description: "Number of bars (bars variant, default 24) or dots (dots variant, default 5).", control: num(3, 48, 1), demo: 24 },
      { name: "sensitivity", type: "number", default: 1, description: "Multiplier applied to the incoming level.", control: num(0.2, 3, 0.1) },
      { name: "smoothing", type: "number", default: 0.75, description: "Frame-to-frame smoothing from 0 (raw) to 0.98 (very smooth).", control: num(0, 0.98, 0.02) },
      { name: "showToggle", type: "boolean", default: true, description: "Show the built-in microphone toggle when source is \"mic\" and active is undefined. Permission errors show a short message.", control: { type: "boolean" } },
      { name: "onLevel", type: "(level: number) => void", description: "Called every frame the smoothed level changes." },
      classNameProp,
    ],
  },
  {
    slug: "ai-recorder",
    name: "AI Recorder",
    exportName: "AiRecorder",
    description: "Voice recorder pill that morphs from a mic button into a live waveform with timer, pause, cancel and stop, then into a scrubbable playback row.",
    category: "AI",
    file: "registry/new-york/ai-recorder/ai-recorder.tsx",
    dependencies: ["motion", "lucide-react"],
    staticProps: ["onRecordingComplete={(blob, ms) => upload(blob)}"],
    isNew: true,
    props: [
      { name: "onRecordingComplete", type: "(blob: Blob, durationMs: number) => void", description: "Called after stop with the recorded audio (MediaRecorder) and its duration. In simulate mode the blob is empty." },
      { name: "maxDuration", type: "number", description: "Stop automatically after this many seconds.", control: num(5, 120, 5, "s"), demo: 30 },
      { name: "simulate", type: "boolean", default: false, description: "Fake the waveform and timer without the microphone. Handy for demos.", control: { type: "boolean" }, demo: true },
      { name: "accent", type: "string", default: "#ff4d12", description: "Color of the stop button, recording dot and played waveform.", control: { type: "color" } },
      { name: "size", type: "number", default: 44, description: "Height of the control in px.", control: num(36, 60, 2, "px") },
      classNameProp,
    ],
  },
  {
    slug: "ai-input",
    name: "AI Input",
    exportName: "AiInput",
    description: "AI prompt box with an auto-growing textarea, cycling placeholders, file chips, model picker, toggle chips and a send button that morphs into stop while streaming.",
    category: "AI",
    file: "registry/new-york/ai-input/ai-input.tsx",
    dependencies: ["motion", "lucide-react"],
    staticProps: ["onSubmit={({ text, files, model }) => send(text)}"],
    isNew: true,
    props: [
      { name: "value", type: "string", description: "Controlled text." },
      { name: "defaultValue", type: "string", default: "", description: "Initial text when uncontrolled." },
      { name: "onValueChange", type: "(value: string) => void", description: "Called whenever the text changes." },
      { name: "onSubmit", type: "(payload: { text, files, model, toggles }) => void", description: "Called on Enter or the send button. Shift+Enter adds a newline." },
      { name: "onStop", type: "() => void", description: "Called when the stop button is pressed while streaming." },
      { name: "status", type: '"idle" | "submitting" | "streaming"', default: "idle", description: "Request state. Streaming turns the send button into a stop button and speeds up the border highlight.", control: { type: "select", options: ["idle", "submitting", "streaming"] } },
      { name: "placeholders", type: "string[]", description: "Example prompts cycled with a soft crossfade while the box is empty." },
      { name: "models", type: "string[]", default: "[\"Auto\", \"Fast\", \"Reasoning\"]", description: "Models offered in the selector. An empty array hides it." },
      { name: "defaultModel", type: "string", description: "Initially selected model. Defaults to the first one." },
      { name: "toggles", type: "{ id: string; label: string; icon?: ReactNode }[]", description: "Toggle chips in the toolbar, such as web search or think. Active ids are sent with onSubmit." },
      { name: "suggestions", type: "string[]", description: "Chips below the box that fill the input on click." },
      { name: "maxRows", type: "number", default: 8, description: "Rows the textarea grows to before scrolling.", control: num(2, 16, 1) },
      { name: "accent", type: "string", default: "#ff4d12", description: "Accent for the send button, focus ring and active chips.", control: { type: "color" } },
      { name: "radius", type: "number", default: 20, description: "Corner radius of the box in px.", control: num(0, 32, 1, "px") },
      { name: "attachments", type: "boolean", default: true, description: "Show the attach button and accept dropped files.", control: { type: "boolean" } },
      { name: "disabled", type: "boolean", default: false, description: "Disable all input.", control: { type: "boolean" } },
      classNameProp,
    ],
  },
  {
    slug: "ai-thinking",
    name: "AI Thinking",
    exportName: "AiThinking",
    description: "Loading and reasoning states for AI responses: shimmering text, bouncing dots, a glowing orb, a collapsible step trace and simulated token streaming.",
    category: "AI",
    file: "registry/new-york/ai-thinking/ai-thinking.tsx",
    dependencies: ["motion", "lucide-react"],
    isNew: true,
    props: [
      { name: "variant", type: '"shimmer" | "dots" | "orb" | "steps" | "stream"', default: "shimmer", description: "Visual style.", control: { type: "select", options: ["shimmer", "dots", "orb", "steps", "stream"] } },
      { name: "label", type: "string", description: "Text for shimmer, dots and orb, and the steps header while running. Shimmer and steps default to \"Thinking…\".", control: { type: "text" }, demo: "Thinking…" },
      { name: "steps", type: "string[]", description: "Reasoning trace for the steps variant. Steps appear one by one, then the header collapses to \"Thought for Ns\"." },
      { name: "activeStep", type: "number", description: "Controlled index of the active step. Values at or past the end mark every step done." },
      { name: "auto", type: "boolean", default: true, description: "Advance steps on a timer when activeStep is undefined.", control: { type: "boolean" } },
      { name: "text", type: "string", description: "Text revealed by the stream variant.", control: { type: "text" }, demo: "Motion should explain, not decorate. Start with one clear transition per interaction, keep durations under 400ms, and let springs carry the weight." },
      { name: "speed", type: "number", default: 60, description: "Stream speed in characters per second.", control: num(10, 200, 5) },
      { name: "duration", type: "number", default: 1400, description: "Cycle length in ms for shimmer, dots and orb; time per step for auto steps.", control: num(400, 4000, 100, "ms") },
      { name: "accent", type: "string", default: "#ff4d12", description: "Color of dots, orb, spinner and checks.", control: { type: "color" } },
      { name: "size", type: '"sm" | "md" | "lg"', default: "md", description: "Overall scale.", control: { type: "select", options: ["sm", "md", "lg"] } },
      { name: "onComplete", type: "() => void", description: "Called once the stream finishes or every step is done." },
      classNameProp,
    ],
  },
]
