import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

export const arcTimelineDocs: ComponentDoc[] = [
  {
    slug: "arc-steps",
    name: "Arc Steps",
    exportName: "ArcSteps",
    description:
      "Pinned \"How it works\" section. A marker travels along a half circle from step to step as you scroll, the passed arc draws in, and the whole section flips to each step's solid color.",
    category: "Scroll",
    file: "registry/new-york/arc-steps/arc-steps.tsx",
    dependencies: ["gsap", "@gsap/react"],
    staticProps: ["steps={steps}"],
    preamble: `const steps = [
  { title: "Install", description: "One command adds the component and its dependencies to your project.", color: "#0a0a0a", foreground: "#ededed" },
  { title: "Customize", description: "It's your code. Tweak props, colors and timing until it feels like yours.", color: "#ff4d12", foreground: "#0a0a0a" },
  { title: "Ship", description: "Server-rendered, accessible and light. Deploy it with the rest of your app.", color: "#f5f0e8", foreground: "#0a0a0a" },
  { title: "Iterate", description: "Pull updates when you want them, keep your changes when you don't.", color: "#1f3a2e", foreground: "#f5f0e8" },
]`,
    isNew: true,
    props: [
      { name: "steps", type: "ArcStep[]", required: true, description: "{ title, description, color, foreground?, icon? }[]. Colors are solid; foreground defaults to black or white for contrast." },
      { name: "position", type: '"bottom" | "top" | "left" | "right"', default: "bottom", description: "Edge the half circle hugs. Bottom reads like a horizon; left and right put the content beside the arc.", control: { type: "select", options: ["bottom", "top", "left", "right"] } },
      { name: "align", type: '"start" | "center" | "end"', default: "center", description: "Text alignment of the step content.", control: { type: "select", options: ["start", "center", "end"] } },
      { name: "arcSize", type: "number", default: 70, description: "Arc radius as a % of the section's shorter side. Clamped so it always fits.", control: num(30, 100, 1, "%") },
      { name: "strokeWidth", type: "number", default: 1.5, description: "Arc stroke width in px.", control: num(0.5, 6, 0.5, "px") },
      { name: "markerSize", type: "number", default: 16, description: "Diameter of the travelling marker in px.", control: num(8, 40, 1, "px") },
      { name: "showNumbers", type: "boolean", default: true, description: "Show step numbers next to each point on the arc.", control: { type: "boolean" } },
      { name: "snap", type: "boolean", default: false, description: "Snap the scroll to the nearest step when scrolling stops.", control: { type: "boolean" } },
      { name: "scrollLength", type: "number", default: 1, description: "Section heights of scroll reserved per step.", control: num(0.5, 3, 0.1) },
      { name: "colorTransition", type: "number", default: 0.8, description: "Duration of the background color change in seconds.", control: num(0, 2, 0.1, "s") },
      { name: "title", type: "string", default: "How it works", description: "Small heading shown in the corner.", control: { type: "text" } },
      { name: "height", type: "string", default: "100vh", description: "Height of the pinned section (any CSS length)." },
      { name: "scroller", type: "HTMLElement | null", description: "Scroll container to track instead of the window." },
      { name: "onStepChange", type: "(index: number) => void", description: "Called with the step index whenever the active step changes." },
      classNameProp,
    ],
  },
  {
    slug: "timeline-scroll",
    name: "Timeline Scroll",
    exportName: "TimelineScroll",
    description:
      "Minimal horizontal timeline of years and milestones. Pins and scrolls sideways with the page, or drags freely with inertia; the year at the center lights up.",
    category: "Scroll",
    file: "registry/new-york/timeline-scroll/timeline-scroll.tsx",
    dependencies: ["gsap", "@gsap/react", "motion"],
    staticProps: ["items={items}"],
    preamble: `const items = [
  { year: 2019, tag: "Day one", title: "Founded", description: "Two engineers, one spare bedroom, a lot of coffee." },
  { year: 2020, tag: "Traction", title: "First 1,000 users", description: "Grew entirely by word of mouth in eight months." },
  { year: 2021, tag: "Funding", title: "Seed round", description: "$3M led by operators who had built it before." },
  { year: 2022, tag: "Team", title: "25 people", description: "Opened our first office and hired across four time zones." },
  { year: 2023, tag: "Funding", title: "Series A", description: "$18M to scale the platform and the team." },
  { year: 2024, tag: "Product", title: "Platform 2.0", description: "Rebuilt from the ground up, ten times faster." },
  { year: 2025, tag: "Scale", title: "Global launch", description: "Live in 40 countries with local payments." },
  { year: 2026, tag: "Today", title: "1M customers", description: "And we're just getting started." },
]`,
    isNew: true,
    props: [
      { name: "items", type: "TimelineScrollItem[]", required: true, description: "{ year, title, description?, tag? }[]" },
      { name: "mode", type: '"scroll" | "drag"', default: "scroll", description: "Scroll pins the section and moves it sideways with vertical scroll. Drag is a free horizontal drag/swipe with inertia and no pinning (arrow keys work too).", control: { type: "select", options: ["scroll", "drag"] } },
      { name: "itemWidth", type: "string", default: "clamp(240px, 44cqw, 560px)", description: "Width of each milestone column (any CSS length).", control: { type: "select", options: ["clamp(240px, 44cqw, 560px)", "clamp(200px, 32cqw, 420px)", "clamp(280px, 60cqw, 720px)"] } },
      { name: "yearSize", type: "string", default: "clamp(3.5rem, min(15cqw, 24cqh), 12rem)", description: "Font size of the years (any CSS length).", control: { type: "select", options: ["clamp(3.5rem, min(15cqw, 24cqh), 12rem)", "clamp(2.5rem, min(10cqw, 16cqh), 8rem)", "clamp(4rem, min(20cqw, 30cqh), 16rem)"] } },
      { name: "accent", type: "string", default: "#ff4d12", description: "Color of the active year, its tick and the progress line.", control: { type: "color" } },
      { name: "showProgress", type: "boolean", default: true, description: "Fill the baseline in the accent color up to the center.", control: { type: "boolean" } },
      { name: "showCounter", type: "boolean", default: true, description: "Rolling year counter in the top-right corner.", control: { type: "boolean" } },
      { name: "align", type: '"top" | "center"', default: "center", description: "Vertical placement of the timeline.", control: { type: "select", options: ["center", "top"] } },
      { name: "scrollLength", type: "number", default: 1, description: "Scroll distance multiplier. Higher = slower horizontal travel.", control: num(0.5, 3, 0.1) },
      { name: "snap", type: "boolean", default: false, description: "Snap to the nearest milestone when scrolling or dragging stops.", control: { type: "boolean" } },
      { name: "title", type: "string", default: "Our journey", description: "Small heading in the top-left corner.", control: { type: "text" } },
      { name: "height", type: "string", default: "100vh", description: "Height of the section (any CSS length)." },
      { name: "scroller", type: "HTMLElement | null", description: "Scroll container to track instead of the window (scroll mode)." },
      classNameProp,
    ],
  },
]
