import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

export const authDocs: ComponentDoc[] = [
  {
    slug: "auth",
    name: "Sign In / Sign Up",
    exportName: "AuthSection",
    description:
      "Sign in and sign up sections built on shadcn inputs: a split onboarding panel, a spotlight card and a multi-step flow with code verification. Animated mode switch, inline validation, loading, success and error states.",
    category: "Forms",
    file: "registry/new-york/auth/auth.tsx",
    dependencies: ["motion", "lucide-react"],
    staticProps: [`providers={["google", "github"]}`, `onSubmit={async (values) => { await signUp(values) }}`],
    isNew: true,
    props: [
      { name: "variant", type: '"split" | "card" | "steps"', default: "split", description: "Two-panel onboarding, centered card, or a multi-step flow (email, code, profile).", control: { type: "select", options: ["split", "card", "steps"] } },
      { name: "mode", type: '"sign-in" | "sign-up"', description: "Controlled mode." },
      { name: "defaultMode", type: '"sign-in" | "sign-up"', default: "sign-up", description: "Initial mode when uncontrolled.", control: { type: "select", options: ["sign-up", "sign-in"] } },
      { name: "onModeChange", type: "(mode: AuthMode) => void", description: "Called when the user switches between sign in and sign up." },
      { name: "title", type: "string | { \"sign-in\"?: string; \"sign-up\"?: string }", description: "Heading. A string, or one per mode. Defaults depend on variant and mode.", control: { type: "text" } },
      { name: "subtitle", type: "string | { \"sign-in\"?: string; \"sign-up\"?: string }", description: "Line under the heading. A string, or one per mode.", control: { type: "text" } },
      { name: "headline", type: "string", default: "Get Started with Us", description: "Split: left panel headline.", control: { type: "text" } },
      { name: "description", type: "string", default: "Complete these easy steps to register your account.", description: "Split: left panel description.", control: { type: "text" } },
      { name: "providers", type: '("google" | "github" | "apple" | "x")[]', default: "[\"google\", \"github\"]", description: "Social sign-in buttons, in order. Pass [] to hide them." },
      { name: "onSubmit", type: "(values: AuthValues) => Promise<void> | void", description: "Receives the form values. Return a promise to show the loading state; reject to show its message and shake the form." },
      { name: "onProviderClick", type: "(provider: AuthProvider) => void", description: "Called when a social button is pressed." },
      { name: "onForgotPassword", type: "() => void", description: "Called when \"Forgot password?\" is pressed." },
      { name: "forgotPasswordHref", type: "string", description: "Renders \"Forgot password?\" as a link instead of a button." },
      { name: "logo", type: "ReactNode", description: "Logo shown above the heading. Nothing is shown when omitted." },
      { name: "accent", type: "string", default: "#ff4d12", description: "Color of primary actions, links and focus rings.", control: { type: "color" } },
      { name: "panelColor", type: "string", default: "#0f3d2e", description: "Split: base color of the left panel.", control: { type: "color" } },
      { name: "glowColor", type: "string", default: "#2f8f73", description: "Split: color of the soft light in the left panel.", control: { type: "color" } },
      { name: "radius", type: "number", default: 24, description: "Corner radius of the outer container.", control: num(0, 40, 1, "px") },
      { name: "steps", type: "string[]", default: "[\"Sign up your account\", \"Set up your workspace\", \"Set up your profile\"]", description: "Split: labels of the three onboarding step cards." },
      { name: "showRememberMe", type: "boolean", default: true, description: "Show the remember-me checkbox when signing in.", control: { type: "boolean" } },
      { name: "magicLink", type: "boolean", default: true, description: "Card: offer a passwordless \"email me a link\" option.", control: { type: "boolean" } },
      { name: "verifyCode", type: "(code: string, email: string) => Promise<boolean> | boolean", description: "Steps: checks the emailed code. Accepts any complete code by default." },
      { name: "onResendCode", type: "(email: string) => void", description: "Steps: called when \"Resend code\" is pressed." },
      { name: "roles", type: "string[]", default: "[\"Designer\", \"Engineer\", \"Founder\", \"Other\"]", description: "Steps: choices for the role picker." },
      { name: "termsHref", type: "string", description: "Terms of service URL. Sign up shows \"By continuing you agree to…\" when this or privacyHref is set.", control: { type: "text" }, demo: "#terms" },
      { name: "privacyHref", type: "string", description: "Privacy policy URL.", control: { type: "text" }, demo: "#privacy" },
      classNameProp,
    ],
  },
]
