import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

const sizeSelect = { type: "select", options: ["sm", "md", "lg"] } as const

export const buttonsBDocs: ComponentDoc[] = [
  {
    slug: "segmented-control",
    name: "Segmented Control",
    exportName: "SegmentedControl",
    description: "Tabs with a springy pill that slides behind the active option, with arrow-key navigation.",
    category: "Buttons",
    file: "registry/new-york/segmented-control/segmented-control.tsx",
    dependencies: ["motion"],
    preamble: `const options = [
  { value: "day", label: "Day" },
  { value: "week", label: "Week" },
  { value: "month", label: "Month" },
]`,
    staticProps: [`options={options}`],
    isNew: true,
    props: [
      { name: "options", type: "{ value: string; label: string; icon?: ReactNode }[]", required: true, description: "Options to choose from, in order." },
      { name: "value", type: "string", description: "Controlled selected value." },
      { name: "defaultValue", type: "string", description: "Initially selected value when uncontrolled. Defaults to the first option." },
      { name: "onValueChange", type: "(value: string) => void", description: "Called with the new value when the selection changes." },
      { name: "size", type: `"sm" | "md" | "lg"`, default: "md", description: "Control size.", control: sizeSelect },
      { name: "pillColor", type: "string", description: "Pill color (any CSS color). Defaults to the theme surface color.", control: { type: "color" } },
      { name: "stiffness", type: "number", default: 400, description: "Spring stiffness of the sliding pill.", control: num(50, 1000, 10) },
      { name: "damping", type: "number", default: 32, description: "Spring damping of the sliding pill.", control: num(5, 60, 1) },
      { name: "aria-label", type: "string", description: "Accessible label for the group." },
      classNameProp,
    ],
  },
  {
    slug: "number-stepper",
    name: "Number Stepper",
    exportName: "NumberStepper",
    description: "Minus / plus stepper whose digits roll individually, with hold-to-repeat and a shake at the limits.",
    category: "Buttons",
    file: "registry/new-york/number-stepper/number-stepper.tsx",
    dependencies: ["motion"],
    isNew: true,
    props: [
      { name: "value", type: "number", description: "Controlled value." },
      { name: "defaultValue", type: "number", demo: 8, description: "Initial value when uncontrolled. Defaults to min.", control: num(0, 100, 1) },
      { name: "onValueChange", type: "(value: number) => void", description: "Called with the new value on every change." },
      { name: "min", type: "number", default: 0, description: "Lowest allowed value.", control: num(-100, 100, 1) },
      { name: "max", type: "number", default: 99, description: "Highest allowed value.", control: num(1, 1000, 1) },
      { name: "step", type: "number", default: 1, description: "Amount added or removed per step.", control: num(0.5, 25, 0.5) },
      { name: "prefix", type: "string", description: "Text shown before the value, e.g. \"$\".", control: { type: "text" } },
      { name: "suffix", type: "string", description: "Text shown after the value, e.g. \"kg\".", control: { type: "text" } },
      { name: "size", type: `"sm" | "md" | "lg"`, default: "md", description: "Control size.", control: sizeSelect },
      { name: "aria-label", type: "string", default: "Quantity", description: "Accessible label for the value." },
      classNameProp,
    ],
  },
  {
    slug: "elastic-switch",
    name: "Elastic Switch",
    exportName: "ElasticSwitch",
    description: "Toggle whose knob stretches while pressed and springs across with overshoot, with optional sun / moon icons.",
    category: "Buttons",
    file: "registry/new-york/elastic-switch/elastic-switch.tsx",
    dependencies: ["motion"],
    isNew: true,
    props: [
      { name: "checked", type: "boolean", description: "Controlled state." },
      { name: "defaultChecked", type: "boolean", default: false, description: "Initial state when uncontrolled.", control: { type: "boolean" } },
      { name: "onCheckedChange", type: "(checked: boolean) => void", description: "Called with the new state when toggled." },
      { name: "size", type: `"sm" | "md" | "lg"`, default: "md", demo: "lg", description: "Switch size.", control: sizeSelect },
      { name: "onColor", type: "string", default: "#ff6a2b", description: "Track color when on.", control: { type: "color" } },
      { name: "offColor", type: "string", description: "Track color when off. Defaults to a muted theme color.", control: { type: "color" } },
      { name: "icons", type: "boolean", default: false, demo: true, description: "Show a sun / moon icon inside the knob.", control: { type: "boolean" } },
      { name: "label", type: "string", demo: "Dark mode", description: "Visible label next to the switch.", control: { type: "text" } },
      { name: "disabled", type: "boolean", default: false, description: "Disable interaction.", control: { type: "boolean" } },
      { name: "aria-label", type: "string", description: "Accessible label when no visible label is given." },
      classNameProp,
    ],
  },
  {
    slug: "expand-input",
    name: "Expand Input",
    exportName: "ExpandInput",
    description: "A pill button that morphs into an email field, then a spinner and a drawn check on submit.",
    category: "Buttons",
    file: "registry/new-york/expand-input/expand-input.tsx",
    dependencies: ["motion"],
    staticProps: [`onSubmit={(email) => subscribe(email)}`],
    isNew: true,
    props: [
      { name: "label", type: "string", default: "Subscribe", description: "Label of the collapsed button.", control: { type: "text" } },
      { name: "placeholder", type: "string", default: "you@example.com", description: "Input placeholder.", control: { type: "text" } },
      { name: "successLabel", type: "string", default: "You're in!", description: "Message shown after a successful submit.", control: { type: "text" } },
      { name: "onSubmit", type: "(value: string) => Promise<unknown> | void", description: "Called with the email. The spinner waits for the promise; a rejection returns to the input." },
      { name: "resetAfter", type: "number", default: 2500, description: "Collapse back to the button after success, in ms (0 = stay).", control: num(0, 8000, 100, "ms") },
      { name: "width", type: "number", default: 300, description: "Width of the expanded input in px.", control: num(200, 480, 10, "px") },
      classNameProp,
    ],
  },
  {
    slug: "rating",
    name: "Rating",
    exportName: "Rating",
    description: "Star rating with a sweeping hover fill, half stars, and a springy pop with sparkles on select.",
    category: "Buttons",
    file: "registry/new-york/rating/rating.tsx",
    dependencies: ["motion"],
    isNew: true,
    props: [
      { name: "value", type: "number", description: "Controlled rating." },
      { name: "defaultValue", type: "number", default: 0, demo: 3.5, description: "Initial rating when uncontrolled.", control: num(0, 10, 0.5) },
      { name: "onValueChange", type: "(value: number) => void", description: "Called with the new rating when the user picks one." },
      { name: "max", type: "number", default: 5, description: "Number of stars.", control: num(1, 10, 1) },
      { name: "allowHalf", type: "boolean", default: true, description: "Allow half-star ratings.", control: { type: "boolean" } },
      { name: "size", type: "number", default: 28, demo: 40, description: "Star size in px.", control: num(12, 72, 1, "px") },
      { name: "color", type: "string", default: "#f59e0b", description: "Fill color.", control: { type: "color" } },
      { name: "readOnly", type: "boolean", default: false, description: "Display only, no interaction.", control: { type: "boolean" } },
      { name: "aria-label", type: "string", default: "Rating", description: "Accessible label." },
      classNameProp,
    ],
  },
]
