import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

const nativeButton = {
  name: "...props",
  type: "ButtonHTMLAttributes",
  description: "Native button attributes are forwarded.",
}

export const buttonsADocs: ComponentDoc[] = [
  {
    slug: "shine-button",
    name: "Shine Button",
    exportName: "ShineButton",
    description: "Pill button with a light beam circling its edge and a soft sheen on hover.",
    category: "Buttons",
    file: "registry/new-york/shine-button/shine-button.tsx",
    dependencies: ["motion"],
    children: "Get started",
    isNew: true,
    props: [
      { name: "children", type: "ReactNode", description: "Button content." },
      { name: "beamColor", type: "string", default: "#ff6a2b", description: "Color of the light that runs around the edge.", control: { type: "color" } },
      { name: "duration", type: "number", default: 3, description: "Seconds for the beam to complete one lap.", control: num(0.5, 10, 0.1, "s") },
      { name: "sheen", type: "boolean", default: true, description: "Sweep a soft sheen across the face on hover.", control: { type: "boolean" } },
      { name: "variant", type: `"solid" | "outline"`, default: "solid", description: "Filled or outlined face.", control: { type: "select", options: ["solid", "outline"] } },
      classNameProp,
      nativeButton,
    ],
  },
  {
    slug: "ripple-button",
    name: "Ripple Button",
    exportName: "RippleButton",
    description: "Material-style ripples that expand from the exact point you press.",
    category: "Buttons",
    file: "registry/new-york/ripple-button/ripple-button.tsx",
    dependencies: ["motion"],
    children: "Click me",
    isNew: true,
    props: [
      { name: "children", type: "ReactNode", description: "Button content." },
      { name: "rippleColor", type: "string", default: "currentColor", description: "Ripple color (any CSS color).", control: { type: "color" }, demo: "#ff6a2b" },
      { name: "duration", type: "number", default: 0.6, description: "Seconds each ripple takes to expand and fade.", control: num(0.2, 2, 0.05, "s") },
      { name: "variant", type: `"solid" | "outline" | "ghost"`, default: "solid", description: "Visual style.", control: { type: "select", options: ["solid", "outline", "ghost"] } },
      classNameProp,
      nativeButton,
    ],
  },
  {
    slug: "hold-button",
    name: "Hold Button",
    exportName: "HoldButton",
    description: "Press and hold to confirm destructive actions. A fill sweeps across while held.",
    category: "Buttons",
    file: "registry/new-york/hold-button/hold-button.tsx",
    dependencies: ["motion"],
    staticProps: [`onConfirm={() => deleteProject()}`],
    isNew: true,
    props: [
      { name: "holdDuration", type: "number", default: 1.2, description: "Seconds the button must be held to confirm.", control: num(0.3, 5, 0.1, "s") },
      { name: "label", type: "string", default: "Hold to delete", description: "Idle label.", control: { type: "text" } },
      { name: "confirmedLabel", type: "string", default: "Deleted", description: "Label shown once confirmed.", control: { type: "text" } },
      { name: "fillColor", type: "string", default: "#ef4444", description: "Color of the fill that sweeps across while holding.", control: { type: "color" } },
      { name: "resetAfter", type: "number", default: 1800, description: "Return to idle after confirming, in ms (0 = stay confirmed).", control: num(0, 6000, 100, "ms") },
      { name: "onConfirm", type: "() => void", description: "Called once the hold completes." },
      classNameProp,
      nativeButton,
    ],
  },
  {
    slug: "slide-button",
    name: "Slide Button",
    exportName: "SlideButton",
    description: "Slide-to-confirm track with a draggable knob, shimmering label and keyboard support.",
    category: "Buttons",
    file: "registry/new-york/slide-button/slide-button.tsx",
    dependencies: ["motion"],
    staticProps: [`onComplete={() => placeOrder()}`],
    isNew: true,
    props: [
      { name: "label", type: "string", default: "Slide to confirm", description: "Text shown on the track.", control: { type: "text" } },
      { name: "completeLabel", type: "string", default: "Confirmed", description: "Text shown once completed.", control: { type: "text" } },
      { name: "threshold", type: "number", default: 0.9, description: "Fraction of the track the knob must pass to complete, 0 to 1.", control: num(0.3, 1, 0.05) },
      { name: "width", type: "number", default: 280, description: "Track width in px.", control: num(200, 480, 10, "px") },
      { name: "accentColor", type: "string", default: "var(--foreground)", description: "Color of the knob and the trailing fill.", control: { type: "color" }, demo: "#ff6a2b" },
      { name: "resetAfter", type: "number", default: 2000, description: "Return to the start after completing, in ms (0 = stay complete).", control: num(0, 6000, 100, "ms") },
      { name: "onComplete", type: "() => void", description: "Called when the knob reaches the end." },
      { name: "disabled", type: "boolean", default: false, description: "Disable interaction.", control: { type: "boolean" } },
      classNameProp,
    ],
  },
  {
    slug: "like-button",
    name: "Like Button",
    exportName: "LikeButton",
    description: "Heart toggle with a spring pop, ring burst, particles and a rolling counter.",
    category: "Buttons",
    file: "registry/new-york/like-button/like-button.tsx",
    dependencies: ["motion", "lucide-react"],
    isNew: true,
    props: [
      { name: "defaultLiked", type: "boolean", default: false, description: "Initial state when uncontrolled.", control: { type: "boolean" } },
      { name: "liked", type: "boolean", description: "Controlled liked state." },
      { name: "onChange", type: "(liked: boolean) => void", description: "Called with the next state when toggled." },
      { name: "count", type: "number", default: 128, description: "Like count, excluding the viewer's own like.", control: num(0, 99999, 1) },
      { name: "color", type: "string", default: "#f43f5e", description: "Heart, ring and particle color.", control: { type: "color" } },
      { name: "size", type: "number", default: 22, description: "Heart size in px.", control: num(14, 64, 1, "px") },
      { name: "particles", type: "number", default: 8, description: "Number of particles in the burst.", control: num(0, 16, 1) },
      classNameProp,
      nativeButton,
    ],
  },
]
