import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

export const cardsDocs: ComponentDoc[] = [
  {
    slug: "product-card",
    name: "Product Card",
    exportName: "ProductCard",
    description:
      "Full-bleed product card with a swipeable image carousel, glass pills, rolling price and an add-to-cart button that morphs into a quantity stepper.",
    category: "Cards",
    file: "registry/new-york/product-card/product-card.tsx",
    dependencies: ["motion", "lucide-react"],
    preamble: `const images = ["/gallery/01.jpg", "/gallery/02.jpg", "/gallery/03.jpg"]`,
    staticProps: [`images={images}`, `badges={["Best Seller"]}`, `onAddToCart={(qty) => console.log("added", qty)}`],
    isNew: true,
    props: [
      { name: "images", type: "string[]", default: "[]", description: "Image URLs for the carousel. Swipe, drag or use the dots. Missing or broken images fall back to a gradient derived from `tint`." },
      { name: "title", type: "string", required: true, description: "Product name.", control: { type: "text" }, demo: "Alphonso" },
      { name: "description", type: "string", description: "Short description, clamped to three lines.", control: { type: "text" }, demo: "Loved worldwide for their sweetness, our Alphonso mangoes are a delicious delight wherever you are." },
      { name: "price", type: "number", default: 0, description: "Price. Digits roll when it changes.", control: num(0, 5000, 10), demo: 270 },
      { name: "prices", type: "number[]", description: "Optional price per image; the price rolls to the matching value when the image changes." },
      { name: "currency", type: "string", default: "₹", description: "Currency symbol before the price.", control: { type: "text" } },
      { name: "locale", type: "string", default: "en-IN", description: "Locale used to format numbers." },
      { name: "compareAt", type: "number", description: "Original price, struck through inside the price pill." },
      { name: "discount", type: "string", description: "Top-right glass pill. Hidden when empty.", control: { type: "text" }, demo: "20% off" },
      { name: "badges", type: "(string | { label: string; icon?: ReactNode })[]", default: "[]", description: "Glass chips under the description." },
      { name: "location", type: "string", description: "Location chip with a pin icon.", control: { type: "text" }, demo: "Kerala" },
      { name: "ctaLabel", type: "string", default: "Add to cart", description: "Button label.", control: { type: "text" } },
      { name: "onAddToCart", type: "(quantity: number) => void", description: "Called with 1 when the button is pressed." },
      { name: "quantity", type: "number", description: "Controlled quantity. 0 shows the button, more shows the stepper." },
      { name: "defaultQuantity", type: "number", default: 0, description: "Initial quantity when uncontrolled.", control: num(0, 10, 1) },
      { name: "onQuantityChange", type: "(quantity: number) => void", description: "Called whenever the quantity changes." },
      { name: "maxQuantity", type: "number", default: 99, description: "Upper bound of the stepper.", control: num(1, 99, 1) },
      { name: "tint", type: "string", default: "#d9870b", description: "Scrim and fallback color. Match it to your photo.", control: { type: "color" } },
      { name: "accent", type: "string", default: "#ffffff", description: "Button background.", control: { type: "color" } },
      { name: "accentForeground", type: "string", default: "#0a0a0a", description: "Button text color.", control: { type: "color" } },
      { name: "radius", type: "number", default: 28, description: "Corner radius.", control: num(0, 48, 1, "px") },
      { name: "aspect", type: "string", default: "3 / 4.4", description: "CSS aspect ratio of the card.", control: { type: "select", options: ["3 / 4.4", "3 / 4", "4 / 5", "1 / 1"] } },
      { name: "autoplay", type: "number | false", default: 0, description: "Advance every N ms, pausing on hover. 0 or false disables.", control: num(0, 8000, 500, "ms") },
      { name: "wishlist", type: "boolean", default: false, description: "Show a wishlist heart top-left.", control: { type: "boolean" }, demo: true },
      { name: "defaultWishlisted", type: "boolean", default: false, description: "Initial wishlist state." },
      { name: "onWishlistChange", type: "(wishlisted: boolean) => void", description: "Called when the heart is toggled." },
      { name: "imageFit", type: '"cover" | "contain"', default: "cover", description: "How images fill the card.", control: { type: "select", options: ["cover", "contain"] } },
      classNameProp,
    ],
  },
  {
    slug: "stamp-card",
    name: "Stamp Card",
    exportName: "StampCard",
    description:
      "Collectible postage stamp with real perforated edges, 3D tilt and glare, and an inked postmark that stamps down on click.",
    category: "Cards",
    file: "registry/new-york/stamp-card/stamp-card.tsx",
    dependencies: ["motion"],
    preamble: `// Also exported: <StampSheet stamps={[...]} />, a fanned stack that spreads on hover`,
    staticProps: [`image="/gallery/04.jpg"`],
    isNew: true,
    props: [
      { name: "image", type: "string", description: "Artwork URL. Missing or broken images fall back to a duotone illustration." },
      { name: "variant", type: '"classic" | "airmail" | "minimal"', default: "classic", description: "Cream paper with a thin frame, red/blue airmail border, or flat duotone. The demo brings the chosen variant to the front.", control: { type: "select", options: ["classic", "airmail", "minimal"] } },
      { name: "title", type: "string", default: "", description: "Title under the artwork.", control: { type: "text" }, demo: "Monsoon Coast" },
      { name: "value", type: "string", default: "₹25", description: "Denomination in the top-right corner.", control: { type: "text" } },
      { name: "country", type: "string", default: "India", description: "Country or brand, also printed around the postmark.", control: { type: "text" } },
      { name: "caption", type: "string", default: "", description: "Small caption next to the country.", control: { type: "text" }, demo: "1972" },
      { name: "paper", type: "string", description: "Paper color. Defaults per variant.", control: { type: "color" } },
      { name: "ink", type: "string", default: "#0a0a0a", description: "Postmark ink color.", control: { type: "color" } },
      { name: "accent", type: "string", default: "#ff4d12", description: "Frames, text and fallback artwork color.", control: { type: "color" } },
      { name: "perforation", type: "number", default: 8, description: "Perforation hole diameter.", control: num(4, 16, 1, "px") },
      { name: "size", type: "number", default: 180, description: "Stamp width; the height snaps to the perforation grid.", control: num(120, 260, 10, "px") },
      { name: "postmarked", type: "boolean", description: "Controlled postmark state." },
      { name: "defaultPostmarked", type: "boolean", default: false, description: "Initial postmark state when uncontrolled.", control: { type: "boolean" } },
      { name: "onPostmark", type: "(postmarked: boolean) => void", description: "Called with the new state when the stamp is clicked." },
      { name: "clickToPostmark", type: "boolean", default: true, description: "Toggle the postmark on click or Enter.", control: { type: "boolean" } },
      { name: "postmarkLabel", type: "string", default: "PAID", description: "Text in the middle of the postmark.", control: { type: "text" } },
      { name: "tilt", type: "number", default: 12, description: "Maximum hover tilt. 0 disables.", control: num(0, 25, 1, "°") },
      { name: "glare", type: "boolean", default: true, description: "Pointer-following glare.", control: { type: "boolean" } },
      { name: "rotate", type: "number", default: 0, description: "Resting rotation.", control: num(-15, 15, 1, "°") },
      classNameProp,
    ],
  },
]
