import { classNameProp, num, type ComponentDoc, type PropDoc } from "@/lib/docs-types"

function baseProps(demo: { title: string; description: string; valueFormat?: string }): PropDoc[] {
  return [
    { name: "title", type: "string", demo: demo.title, description: "Card heading.", control: { type: "text" } },
    { name: "description", type: "string", demo: demo.description, description: "Small line under the heading.", control: { type: "text" } },
    { name: "titleSize", type: `"hero" | "default"`, default: "default", description: "\"hero\" is a huge bold heading; \"default\" is a compact dashboard header.", control: { type: "select", options: ["default", "hero"] } },
    { name: "surface", type: `"dark" | "light"`, default: "dark", description: "Card surface; every color derives from it.", control: { type: "select", options: ["dark", "light"] } },
    { name: "accent", type: "string", default: "#FF4D12", description: "Main accent color.", control: { type: "color" } },
    { name: "palette", type: "string[]", description: "Colors in order; overrides the accent-derived palette." },
    { name: "icon", type: "ReactNode", description: "Content of the round badge in the top-right corner. Pass null to hide it." },
    { name: "radius", type: "number", default: 28, description: "Card corner radius in px.", control: num(0, 40, 1, "px") },
    { name: "bare", type: "boolean", default: false, description: "Render only the chart, without the card.", control: { type: "boolean" } },
    { name: "animate", type: "boolean", default: true, description: "Play the entrance animation.", control: { type: "boolean" } },
    { name: "duration", type: "number", default: 1.2, description: "Entrance duration in seconds.", control: num(0.2, 4, 0.1, "s") },
    { name: "delay", type: "number", default: 0, description: "Delay before the entrance starts, in seconds.", control: num(0, 2, 0.1, "s") },
    { name: "once", type: "boolean", default: true, description: "Animate only the first time the chart enters view.", control: { type: "boolean" } },
    { name: "valueFormat", type: `"number" | "compact" | "percent" | "currency" | ((value: number) => string)`, default: "number", demo: demo.valueFormat, description: "How values are formatted in labels, legends and tooltips.", control: { type: "select", options: ["number", "compact", "percent", "currency"] } },
    { name: "currency", type: "string", default: "USD", description: "Currency code used when valueFormat is \"currency\".", control: { type: "text" } },
    { name: "decimals", type: "number", description: "Fraction digits for formatted values. Defaults to automatic." },
    classNameProp,
  ]
}

export const chartsPolarDocs: ComponentDoc[] = [
  {
    slug: "chart-radial",
    name: "Chart Radial",
    exportName: "ChartRadial",
    description:
      "Donut, pie or gauge from your rows. Slices sweep in one after another, re-flow when toggled from the legend and pop out on hover.",
    category: "Charts",
    file: "registry/new-york/chart-radial/chart-radial.tsx",
    dependencies: ["motion"],
    staticProps: [`nameKey="browser"`, `valueKey="visitors"`],
    isNew: true,
    props: [
      {
        name: "data",
        type: "ChartDatum[]",
        required: true,
        description: "Rows to plot, one slice per row.",
        control: { type: "data" },
        demo: [
          { browser: "Chrome", visitors: 275 },
          { browser: "Safari", visitors: 200 },
          { browser: "Firefox", visitors: 187 },
          { browser: "Edge", visitors: 173 },
          { browser: "Other", visitors: 90 },
        ],
      },
      { name: "nameKey", type: "string", required: true, description: "Key holding each slice's name, e.g. \"browser\"." },
      { name: "valueKey", type: "string", required: true, description: "Key holding each slice's value, e.g. \"visitors\"." },
      { name: "colorKey", type: "string", description: "Optional key holding a CSS color per row." },
      { name: "textures", type: "ChartTexture[]", default: "[\"solid\", \"hatch\", \"solid\", \"muted\", \"hatch\", \"muted\"]", description: "Fill styles cycled per slice: \"solid\", \"hatch\", \"dots\" or \"muted\"." },
      { name: "innerRadius", type: "number", default: 0.62, description: "Hole size as a fraction of the radius; 0 draws a pie.", control: num(0, 0.9, 0.01) },
      { name: "padAngle", type: "number", default: 1.5, description: "Gap between slices in degrees.", control: num(0, 8, 0.5, "°") },
      { name: "cornerRadius", type: "number", default: 4, description: "Rounding of slice corners in px.", control: num(0, 16, 1, "px") },
      { name: "startAngle", type: "number", default: 0, description: "Where the first slice starts, in degrees (0 = 12 o'clock).", control: num(-180, 180, 5, "°") },
      { name: "endAngle", type: "number", default: 360, description: "Where the last slice ends. Use -90 / 90 for a half-circle gauge.", control: num(-90, 360, 5, "°") },
      { name: "showLabels", type: `"none" | "percent" | "value" | "name"`, default: "percent", description: "Text drawn on each slice; hidden on slices too small to fit it.", control: { type: "select", options: ["none", "percent", "value", "name"] } },
      { name: "center", type: `"total" | "active" | "none"`, default: "total", description: "Content of the hole. \"total\" switches to the hovered slice; \"active\" shows the hovered, highlighted or largest slice's share.", control: { type: "select", options: ["total", "active", "none"] } },
      { name: "centerLabel", type: "string", default: "Total", demo: "Visitors", description: "Caption under the total.", control: { type: "text" } },
      { name: "highlight", type: "number", demo: 0, description: "Index (after sorting) of a slice pushed outward.", control: num(0, 9, 1) },
      { name: "hoverEffect", type: `"explode" | "dim" | "none"`, default: "explode", description: "What hovering a slice does.", control: { type: "select", options: ["explode", "dim", "none"] } },
      { name: "showLegend", type: "boolean", default: true, description: "Legend with values and shares; click a row to toggle its slice.", control: { type: "boolean" } },
      { name: "showTooltip", type: "boolean", default: false, description: "Show a tooltip next to the pointer.", control: { type: "boolean" } },
      { name: "size", type: "number", default: 220, description: "Chart diameter in px.", control: num(120, 360, 10, "px") },
      { name: "sortBy", type: `"none" | "value"`, default: "none", description: "Slice order.", control: { type: "select", options: ["none", "value"] } },
      ...baseProps({ title: "Traffic by browser", description: "Last 30 days" }),
    ],
  },
  {
    slug: "chart-rings",
    name: "Chart Rings",
    exportName: "ChartRings",
    description:
      "Concentric progress rings against per-row goals. Rings fill with a springy stagger, numbers count up and overshoot draws a second lap.",
    category: "Charts",
    file: "registry/new-york/chart-rings/chart-rings.tsx",
    dependencies: ["motion"],
    staticProps: [`nameKey="goal"`, `valueKey="value"`, `maxKey="target"`],
    isNew: true,
    props: [
      {
        name: "data",
        type: "ChartDatum[]",
        required: true,
        description: "Rows to plot, one ring per row, outermost first.",
        control: { type: "data" },
        demo: [
          { goal: "Move", value: 420, target: 600 },
          { goal: "Exercise", value: 38, target: 30 },
          { goal: "Stand", value: 9, target: 12 },
        ],
      },
      { name: "nameKey", type: "string", required: true, description: "Key holding each ring's name, e.g. \"goal\"." },
      { name: "valueKey", type: "string", required: true, description: "Key holding each ring's current value." },
      { name: "maxKey", type: "string", description: "Key holding a per-row goal; falls back to max." },
      { name: "max", type: "number", default: 100, description: "Goal used when a row has no maxKey value.", control: num(1, 1000, 1) },
      { name: "colorKey", type: "string", description: "Optional key holding a CSS color per row." },
      { name: "thickness", type: "number", default: 14, description: "Ring thickness in px.", control: num(4, 32, 1, "px") },
      { name: "gap", type: "number", default: 6, description: "Space between rings in px.", control: num(0, 20, 1, "px") },
      { name: "trackTexture", type: `"solid" | "hatch" | "none"`, default: "hatch", description: "Style of the unfilled track.", control: { type: "select", options: ["solid", "hatch", "none"] } },
      { name: "roundedCaps", type: "boolean", default: true, description: "Round the ends of each ring.", control: { type: "boolean" } },
      { name: "startAngle", type: "number", default: 0, description: "Where rings start filling, in degrees (0 = 12 o'clock).", control: num(-180, 180, 5, "°") },
      { name: "showValues", type: `"percent" | "value" | "none"`, default: "percent", description: "What the list next to the rings shows.", control: { type: "select", options: ["percent", "value", "none"] } },
      { name: "layout", type: `"side" | "stacked"`, default: "side", description: "List beside the rings or stacked under them.", control: { type: "select", options: ["side", "stacked"] } },
      { name: "size", type: "number", default: 200, description: "Chart diameter in px.", control: num(120, 320, 10, "px") },
      ...baseProps({ title: "Daily goals", description: "Today, 6:40 PM" }),
    ],
  },
  {
    slug: "chart-radar",
    name: "Chart Radar",
    exportName: "ChartRadar",
    description:
      "Spider chart comparing series across axes. The grid draws in, polygons spring out from the center and hovering an axis lists every value.",
    category: "Charts",
    file: "registry/new-york/chart-radar/chart-radar.tsx",
    dependencies: ["motion"],
    staticProps: [`index="metric"`, `series={[{ key: "team", label: "Team" }, { key: "benchmark", label: "Benchmark" }]}`],
    isNew: true,
    props: [
      {
        name: "data",
        type: "ChartDatum[]",
        required: true,
        description: "Rows to plot, one axis per row.",
        control: { type: "data" },
        demo: [
          { metric: "Speed", team: 86, benchmark: 72 },
          { metric: "Quality", team: 78, benchmark: 80 },
          { metric: "Uptime", team: 94, benchmark: 88 },
          { metric: "Security", team: 70, benchmark: 76 },
          { metric: "Cost", team: 62, benchmark: 70 },
          { metric: "Support", team: 88, benchmark: 65 },
        ],
      },
      { name: "index", type: "string", required: true, description: "Key holding each axis label, e.g. \"metric\"." },
      { name: "series", type: "ChartSeries[]", required: true, description: "Series drawn as polygons: { key, label?, color?, texture? }." },
      { name: "max", type: "number", description: "Value at the outer ring. Defaults to a nice number above the largest value." },
      { name: "levels", type: "number", default: 4, description: "Number of grid rings.", control: num(1, 8, 1) },
      { name: "gridShape", type: `"polygon" | "circle"`, default: "polygon", description: "Shape of the grid rings.", control: { type: "select", options: ["polygon", "circle"] } },
      { name: "fillOpacity", type: "number", default: 0.25, description: "Opacity of solid fills; textured fills scale with it.", control: num(0, 1, 0.05) },
      { name: "showPoints", type: "boolean", default: true, description: "Draw a dot at every value.", control: { type: "boolean" } },
      { name: "showAxisLabels", type: "boolean", default: true, description: "Show axis labels around the chart.", control: { type: "boolean" } },
      { name: "showLevelLabels", type: "boolean", default: false, description: "Show each ring's value on the top axis.", control: { type: "boolean" } },
      { name: "showTooltip", type: "boolean", default: true, description: "Hovering an axis highlights it and lists every series' value.", control: { type: "boolean" } },
      { name: "showLegend", type: "boolean", default: true, description: "Legend; click an item to toggle its series.", control: { type: "boolean" } },
      { name: "size", type: "number", default: 260, description: "Chart height in px; labels get extra room on the sides.", control: num(160, 360, 10, "px") },
      { name: "curve", type: `"linear" | "smooth"`, default: "linear", description: "Polygon edges: straight or a closed smooth curve.", control: { type: "select", options: ["linear", "smooth"] } },
      ...baseProps({ title: "Team vs. benchmark", description: "Q3 engineering scorecard" }),
    ],
  },
]
