import { classNameProp, num, type ComponentDoc } from "@/lib/docs-types"

export const faqConfettiDocs: ComponentDoc[] = [
  {
    slug: "faq",
    name: "FAQ",
    exportName: "Faq",
    description:
      "Animated FAQ accordion in four styles, with height-auto reveals, a live filter that collapses non-matching items and full keyboard support.",
    category: "Sections",
    file: "registry/new-york/faq/faq.tsx",
    dependencies: ["motion", "lucide-react"],
    staticProps: ["items={items}"],
    preamble: `const items = [
  { question: "Can I change plans later?", answer: "Yes. Upgrades apply instantly and downgrades take effect at the end of your billing period." },
  { question: "Do you offer refunds?", answer: "Annual plans can be refunded in full within 30 days, no questions asked." },
]`,
    isNew: true,
    props: [
      { name: "items", type: "{ question: string; answer: ReactNode; id?: string }[]", required: true, description: "Questions and answers. Plain string answers get the richest reveal animations." },
      { name: "variant", type: '"minimal" | "cards" | "numbered" | "split"', default: "minimal", description: "Hairline list, lifting cards, large display numerals, or a two-column list with an answer panel.", control: { type: "select", options: ["minimal", "cards", "numbered", "split"] } },
      { name: "type", type: '"single" | "multiple"', default: "single", description: "Allow one or many items open at once. The split variant is always single.", control: { type: "select", options: ["single", "multiple"] } },
      { name: "defaultOpen", type: "number | number[]", description: "Index or indices open initially when uncontrolled.", demo: 0, control: num(0, 5, 1) },
      { name: "value", type: "number[]", description: "Controlled open indices." },
      { name: "onValueChange", type: "(value: number[]) => void", description: "Called with the new open indices whenever an item toggles." },
      { name: "icon", type: '"plus" | "chevron" | "arrow"', default: "plus", description: "Trigger icon. Plus rotates into an ×, chevron flips, arrow turns down.", control: { type: "select", options: ["plus", "chevron", "arrow"] } },
      { name: "accent", type: "string", default: "#ff4d12", description: "Accent for highlights, rings, numerals and indicators (any CSS color).", control: { type: "color" } },
      { name: "title", type: "string", description: "Optional section heading.", demo: "Frequently asked questions", control: { type: "text" } },
      { name: "description", type: "string", description: "Optional text under the heading.", control: { type: "text" } },
      { name: "searchable", type: "boolean", default: false, description: "Show a filter input. Non-matching items collapse out and matches highlight.", control: { type: "boolean" } },
      { name: "searchPlaceholder", type: "string", default: "Search questions", description: "Placeholder and label of the filter input.", control: { type: "text" } },
      { name: "stagger", type: "number", default: 0.06, description: "Delay between items when the list scrolls into view, in seconds. 0 disables the entrance.", control: num(0, 0.3, 0.01, "s") },
      { name: "duration", type: "number", default: 0.45, description: "Open and close duration in seconds.", control: num(0.1, 1.5, 0.05, "s") },
      { name: "radius", type: "number", default: 16, description: "Corner radius of cards, panels and the search field.", control: num(0, 32, 1, "px") },
      classNameProp,
    ],
  },
  {
    slug: "confetti",
    name: "Confetti",
    exportName: "ConfettiButton",
    description:
      "High-performance canvas confetti with bursts, cannons, fireworks, rain and streams. Ships an imperative confetti() function, a useConfetti hook, a button and a declarative component.",
    category: "Feedback",
    file: "registry/new-york/confetti/confetti.tsx",
    dependencies: ["motion"],
    children: "Ship it",
    preamble: `// Also exported: confetti(options), useConfetti(ref?) and <Confetti trigger="mount" />
// import { confetti } from "@/components/confetti"
// await confetti({ preset: "fireworks", colors: ["#ff4d12", "#ededed"] })`,
    isNew: true,
    props: [
      { name: "preset", type: '"burst" | "cannons" | "fireworks" | "rain" | "pride" | "stream"', default: "burst", description: "Effect preset. Cannons fire from both bottom corners, fireworks launch rockets that explode, rain falls from the top, pride and stream shoot from both sides.", control: { type: "select", options: ["burst", "cannons", "fireworks", "rain", "pride", "stream"] } },
      { name: "particleCount", type: "number", default: 90, description: "Particles per shot (per cannon, per firework). For rain and streams, the total over duration. Default depends on the preset.", control: num(10, 400, 10) },
      { name: "spread", type: "number", default: 70, description: "Cone width in degrees. Default depends on the preset.", control: num(10, 360, 5, "°") },
      { name: "angle", type: "number", default: 90, description: "Launch direction in degrees. 90 is straight up.", control: num(0, 180, 5, "°") },
      { name: "startVelocity", type: "number", default: 45, description: "Initial speed in px per frame. Default depends on the preset.", control: num(5, 90, 1) },
      { name: "gravity", type: "number", default: 1, description: "Gravity multiplier.", control: num(0, 3, 0.1) },
      { name: "drift", type: "number", default: 0, description: "Constant sideways drift. Negative drifts left.", control: num(-3, 3, 0.1) },
      { name: "decay", type: "number", default: 0.9, description: "Velocity kept each frame (0 to 1). Lower stops particles faster.", control: num(0.8, 0.99, 0.01) },
      { name: "scalar", type: "number", default: 1, description: "Particle size multiplier.", control: num(0.4, 3, 0.1) },
      { name: "ticks", type: "number", default: 200, description: "Particle lifetime in frames (60 per second).", control: num(60, 600, 10) },
      { name: "duration", type: "number", default: 2.5, description: "Length of timed presets (fireworks, rain, pride, stream) in seconds. Default depends on the preset.", control: num(0.5, 8, 0.5, "s") },
      { name: "origin", type: "{ x?: number; y?: number }", description: "Launch point as a fraction of the viewport (0 to 1). The button defaults to its own center." },
      { name: "colors", type: "string[]", description: 'Particle colors. Default: ["#ff4d12", "#ff8a4c", "#ffd2b8", "#ededed", "#8a8a8a", "#0a0a0a"].' },
      { name: "shapes", type: '("square" | "circle" | "strip" | "star")[]', description: 'Particle shapes, picked at random. Default: ["square", "circle", "strip"].' },
      { name: "emoji", type: "string[]", description: "Render these emoji as particles instead of shapes." },
      { name: "zIndex", type: "number", default: 100, description: "z-index of the full-viewport canvas." },
      { name: "disableForReducedMotion", type: "boolean", default: true, description: "Do nothing when the user prefers reduced motion.", control: { type: "boolean" } },
      { name: "color", type: "string", default: "#ff4d12", description: "Button background (any CSS color).", control: { type: "color" } },
      { name: "children", type: "ReactNode", default: "Celebrate", description: "Button label." },
      classNameProp,
    ],
  },
]
